name: 'Otus C++ Prof final project `producer-consumer`'

on:
  push:
    branches:
      - master
      - feature/github_actions
  # позволяет запускать workflow вручную с вкладки actions в интерфейсе github.com
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # при выполнении задания будет доступен наш репозиторий
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./prodcon-0.0.${{ github.run_number }}-Linux.deb
          asset_name: prodcon-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
  build_doc:
    runs-on: ubuntu-latest
    steps:
      # при выполнении задания будет доступен наш репозиторий, вызвает git fetch
      - uses: actions/checkout@v2

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.1

      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages